# Model arguments
model_name_or_path: Qwen/Qwen1.5-7B-Chat
tokenizer_name_or_path: arpitsh018/qwen-bos-tokenizer
torch_dtype: bfloat16

# Data training arguments
dataset_mixer:
  communityai/system_identity_preference: 1.0
  argilla/distilabel-capybara-dpo-7k-binarized: 1.0
dataset_splits:
- train
preprocessing_num_workers: 12

# ORPOTrainer arguments
bf16: true
beta: 0.05
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: qwen1.5-7b-chat-orpo-v2
learning_rate: 5.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: inverse_sqrt
max_length: 4096
max_prompt_length: 3800
num_train_epochs: 3
optim: adamw_bnb_8bit
output_dir: data/qwen1.5-7b-chat-orpo-v2
per_device_train_batch_size: 2
push_to_hub: true
report_to:
- tensorboard
- wandb
save_strategy: "no"
seed: 42
warmup_steps: 100